def updateParameterDict(pDict):
	pDict['__________SSC_MTRX_PRM_SECTION'].valueChange('enable', 'X' in pDict["LITHOLOGY_MODEL"].value('value'))
	pDict['NPHI_FLUID'].valueChange('enable', pDict["DNXPLOTSAND"].value('value') == 'LINEAR' and pDict["LITHOLOGY_MODEL"].value('value') == 'SSC')
	pDict['RHOB_FLUID'].valueChange('enable', pDict["LITHOLOGY_MODEL"].value('value') == 'SSC')
	pDict['NPHI_DRY_SAND'].valueChange('enable', pDict["DNXPLOTSAND"].value('value') == 'LINEAR' and pDict["LITHOLOGY_MODEL"].value('value') == 'SSC')
	pDict['RHOB_DRY_SAND'].valueChange('enable', pDict["LITHOLOGY_MODEL"].value('value') == 'SSC')
	pDict['RHOB_DRY_SLT'].valueChange('enable', pDict["LITHOLOGY_MODEL"].value('value') == 'SSC')
	pDict['NPHI_OFFSET'].valueChange('enable', pDict["DNXPLOTSAND"].value('value') != 'LINEAR' and pDict["LITHOLOGY_MODEL"].value('value') == 'SSC')
	pDict['__________SSC_WCLAY_PRM_SECTION'].valueChange('enable', 'X' in pDict["LITHOLOGY_MODEL"].value('value'))
	pDict['NPHI_CLY'].valueChange('enable', pDict["LITHOLOGY_MODEL"].value('value') == 'SSC')
	pDict['RHOB_CLY'].valueChange('enable', pDict["LITHOLOGY_MODEL"].value('value') == 'SSC')
	pDict['__________SILT_LINE_PRM_SECTION'].valueChange('enable', 'X' in pDict["LITHOLOGY_MODEL"].value('value'))
	pDict['USE_SILT_ANGLE'].valueChange('enable', pDict["LITHOLOGY_MODEL"].value('value') == 'SSC')
	pDict['DEGFLSLT'].valueChange('enable', pDict["USE_SILT_ANGLE"].value('value') == 'YES' and pDict["LITHOLOGY_MODEL"].value('value') == 'SSC')
	pDict['SILTLINE_RATIO'].valueChange('enable', pDict["USE_SILT_ANGLE"].value('value') == 'NO' and pDict["LITHOLOGY_MODEL"].value('value') == 'SSC')
	pDict['DNXPLOTSAND'].valueChange('enable',  pDict["LITHOLOGY_MODEL"].value('value') == 'SSC')
	pDict['TERNARY_DEPTH'].valueChange('enable', pDict["LITHOLOGY_MODEL"].value('value') == 'SSC' and pDict["SSC_DN_CROSSPLOT"].value('value') == 'YES')
	pDict['TERNARY_INTERVAL'].valueChange('enable', pDict["LITHOLOGY_MODEL"].value('value') == 'SSC' and pDict["SSC_DN_CROSSPLOT"].value('value') == 'YES')
	pDict['__________VSHGR_PRM_SECTION'].valueChange('enable', 'X' in pDict["LITHOLOGY_MODEL"].value('value'))
	pDict['GR_CL'].valueChange('enable', pDict["LITHOLOGY_MODEL"].value('value') == 'SSC')
	pDict['GR_SD'].valueChange('enable', pDict["LITHOLOGY_MODEL"].value('value') == 'SSC')
	pDict['__________SSC_XPLOT_SECTION'].valueChange('enable', 'X' in pDict["LITHOLOGY_MODEL"].value('value'))
	pDict['SSC_DN_CROSSPLOT'].valueChange('enable', pDict["LITHOLOGY_MODEL"].value('value') == 'SSC')
	pDict['__________CARB_MDL_PRM_SECTION'].valueChange('enable', 'X' in pDict["LITHOLOGY_MODEL"].value('value'))
	pDict['LITHTYPE'].valueChange('enable', pDict["LITHOLOGY_MODEL"].value('value') == 'CARB' or pDict['CARSTFL'].value('value')=='YES')
	pDict['CLAYFLG'].valueChange('enable', pDict["LITHOLOGY_MODEL"].value('value') == 'CARB' or pDict['CARSTFL'].value('value')=='YES')
	pDict['NEUTOOL'].valueChange('enable', pDict["LITHOLOGY_MODEL"].value('value') == 'CARB' and ('DL' in pDict["LITHTYPE"].value('value') or 'QZ' in  pDict["LITHTYPE"].value('value')))
	pDict['LITH2FLG'].valueChange('enable', pDict["LITHOLOGY_MODEL"].value('value') == 'CARB' and len(pDict["LITHTYPE"].value('value')) == 10)
	pDict['__________CARB_MTRX_PRM_SECTION'].valueChange('enable', 'X' in pDict["LITHOLOGY_MODEL"].value('value'))
	pDict['RHOB_FLC'].valueChange('enable', pDict["LITHOLOGY_MODEL"].value('value') == 'CARB')
	pDict['RHOB_DRYLM'].valueChange('enable', pDict["LITHOLOGY_MODEL"].value('value') == 'CARB' and 'CA' in pDict["LITHTYPE"].value('value') and pDict["LITH2FLG"].value('value') != 'PEF_ONLY')
	pDict['NPHI_DRYLM'].valueChange('enable', pDict["LITHOLOGY_MODEL"].value('value') == 'CARB' and 'CA' in pDict["LITHTYPE"].value('value'))
	pDict['PEF_DRYLM'].valueChange('enable', pDict["LITHOLOGY_MODEL"].value('value') == 'CARB' and 'CA' in pDict["LITHTYPE"].value('value') and len(pDict["LITHTYPE"].value('value')) >= 10)
	pDict['RHOB_DRYDL'].valueChange('enable', pDict["LITHOLOGY_MODEL"].value('value') == 'CARB' and 'DL' in pDict["LITHTYPE"].value('value')and pDict["LITH2FLG"].value('value') != 'PEF_ONLY')
	pDict['NPHI_DRYDL'].valueChange('enable', pDict["LITHOLOGY_MODEL"].value('value') == 'CARB' and 'DL' in pDict["LITHTYPE"].value('value'))
	pDict['PEF_DRYDL'].valueChange('enable', pDict["LITHOLOGY_MODEL"].value('value') == 'CARB' and 'DL' in pDict["LITHTYPE"].value('value') and len(pDict["LITHTYPE"].value('value')) >= 10)
	pDict['RHOB_DRYQZ'].valueChange('enable', pDict["LITHOLOGY_MODEL"].value('value') == 'CARB' and 'QZ' in pDict["LITHTYPE"].value('value') and pDict["LITH2FLG"].value('value') != 'PEF_ONLY')
	pDict['NPHI_DRYQZ'].valueChange('enable', pDict["LITHOLOGY_MODEL"].value('value') == 'CARB' and ('QZ' in pDict["LITHTYPE"].value('value')))
	pDict['PEF_DRYQZ'].valueChange('enable', pDict["LITHOLOGY_MODEL"].value('value') == 'CARB' and 'QZ' in pDict["LITHTYPE"].value('value') )
	pDict['RHOB_DRYMIN1'].valueChange('enable', pDict["LITHOLOGY_MODEL"].value('value') == 'CARB' and 'M1' in pDict["LITHTYPE"].value('value') and ('CA-M1-M2' in pDict["LITHTYPE"].value('value') or 'CA-M1-[CL]' in pDict["LITHTYPE"].value('value')))
	pDict['NPHI_DRYMIN1'].valueChange('enable', pDict["LITHOLOGY_MODEL"].value('value') == 'CARB' and 'M1' in pDict["LITHTYPE"].value('value') and ('CA-M1-M2' in pDict["LITHTYPE"].value('value') or 'CA-M1-[CL]' in pDict["LITHTYPE"].value('value')))
	pDict['PEF_DRYMIN1'].valueChange('enable', pDict["LITHOLOGY_MODEL"].value('value') == 'CARB' and 'M1' in pDict["LITHTYPE"].value('value') and ('CA-M1-M2' in pDict["LITHTYPE"].value('value') or 'CA-M1-[CL]' in pDict["LITHTYPE"].value('value')))
	pDict['RHOB_DRYMIN2'].valueChange('enable', pDict["LITHOLOGY_MODEL"].value('value') == 'CARB' and 'M2' in pDict["LITHTYPE"].value('value') and 'CA-M1-M2' in pDict["LITHTYPE"].value('value'))
	pDict['NPHI_DRYMIN2'].valueChange('enable', pDict["LITHOLOGY_MODEL"].value('value') == 'CARB' and 'M2' in pDict["LITHTYPE"].value('value') and 'CA-M1-M2' in pDict["LITHTYPE"].value('value'))
	pDict['PEF_DRYMIN2'].valueChange('enable', pDict["LITHOLOGY_MODEL"].value('value') == 'CARB' and 'M2' in pDict["LITHTYPE"].value('value') and 'CA-M1-M2' in pDict["LITHTYPE"].value('value'))
	pDict['RHOB_DRYCLY'].valueChange('enable', pDict["LITHOLOGY_MODEL"].value('value') == 'CARB' and pDict["CLAYFLG"].value('value') == 'YES' and pDict["LITH2FLG"].value('value') != 'PEF_ONLY')
	pDict['PEF_DRYCLY'].valueChange('enable', pDict["LITHOLOGY_MODEL"].value('value') == 'CARB' and pDict["CLAYFLG"].value('value') == 'YES')
	pDict['NEU_OFFSET'].valueChange('enable', pDict["LITHOLOGY_MODEL"].value('value') == 'CARB')
	pDict['PEF_OFFSET'].valueChange('enable', pDict["LITHOLOGY_MODEL"].value('value') == 'CARB' and len(pDict["LITHTYPE"].value('value')) == 10 or 'CA-DL-QZ' in pDict["LITHTYPE"].value('value') or 'CA-M1-M2' in pDict["LITHTYPE"].value('value')  )
	pDict['__________CARB_WCLAY_PRM_SECTION'].valueChange('enable', 'X' in pDict["LITHOLOGY_MODEL"].value('value'))
	pDict['RHOB_WCL'].valueChange('enable', (pDict["LITHOLOGY_MODEL"].value('value') == 'CARB' or pDict['CARSTFL'].value('value')=='YES') and pDict["CLAYFLG"].value('value') == 'YES' and len(pDict["LITHTYPE"].value('value')) == 7)
	pDict['NPHI_WCL'].valueChange('enable', (pDict["LITHOLOGY_MODEL"].value('value') == 'CARB' or pDict['CARSTFL'].value('value')=='YES') and pDict["CLAYFLG"].value('value') == 'YES' and len(pDict["LITHTYPE"].value('value')) == 7)
	pDict['__________VCLGR_PRM_SECTION'].valueChange('enable', 'X' in pDict["LITHOLOGY_MODEL"].value('value'))
	pDict['GR_CLN'].valueChange('enable', (pDict["LITHOLOGY_MODEL"].value('value') == 'CARB' and pDict["CLAYFLG"].value('value') == 'YES' and len(pDict["LITHTYPE"].value('value')) != 7) or (pDict['CARSTFL'].value('value')=='YES' and pDict["CLAYFLG"].value('value') == 'YES' and 'CA-QZ-[CL]' in pDict["LITHTYPE"].value('value')))
	pDict['GR_CLY'].valueChange('enable', (pDict["LITHOLOGY_MODEL"].value('value') == 'CARB' and pDict["CLAYFLG"].value('value') == 'YES' and len(pDict["LITHTYPE"].value('value')) != 7) or (pDict['CARSTFL'].value('value')=='YES' and pDict["CLAYFLG"].value('value') == 'YES' and 'CA-QZ-[CL]' in pDict["LITHTYPE"].value('value')))
	pDict['GR_CALC'].valueChange('enable', (pDict["LITHOLOGY_MODEL"].value('value') == 'CARB' and pDict["CLAYFLG"].value('value') == 'YES' and len(pDict["LITHTYPE"].value('value')) != 7) or (pDict['CARSTFL'].value('value')=='YES' and pDict["CLAYFLG"].value('value') == 'YES' and 'CA-QZ-[CL]' in pDict["LITHTYPE"].value('value')))
	pDict['__________CARB_XPLOT_SECTION'].valueChange('enable', 'X' in pDict["LITHOLOGY_MODEL"].value('value'))
	pDict['CARB_XPLOT'].valueChange('enable', pDict["LITHOLOGY_MODEL"].value('value') == 'CARB')
	pDict['CARB_TERNARY_DEPTH'].valueChange('enable', pDict["LITHOLOGY_MODEL"].value('value') == 'CARB' and pDict["CARB_XPLOT"].value('value') == 'YES')
	pDict['CARB_TERNARY_INTERVAL'].valueChange('enable', pDict["LITHOLOGY_MODEL"].value('value') == 'CARB' and pDict["CARB_XPLOT"].value('value') == 'YES')
	pDict['DEPTHSOURCE'].valueChange('enable', pDict["TEMPSOURCE"].value('value') == 'CALCULATED')
	pDict['WELLLOC'].valueChange('enable', pDict["TEMPSOURCE"].value('value') == 'CALCULATED')
	pDict['RTKB_DEP'].valueChange('enable', pDict["TEMPSOURCE"].value('value') == 'CALCULATED')
	pDict['SURF_TEMP'].valueChange('enable', pDict["TEMPSOURCE"].value('value') == 'CALCULATED')
	pDict['TD_MD'].valueChange('enable', pDict["DEPTHSOURCE"].value('value') == 'DEPTH_MD' and pDict["TEMPSOURCE"].value('value') == 'CALCULATED')
	pDict['TD_TVDSS'].valueChange('enable', pDict["DEPTHSOURCE"].value('value') == 'DEPTH_TVDSS' and pDict["TEMPSOURCE"].value('value') == 'CALCULATED')
	pDict['BHT_TEMP'].valueChange('enable', pDict["TEMPSOURCE"].value('value') == 'CALCULATED')	
	pDict['SB_DEP'].valueChange('enable', pDict["WELLLOC"].value('value') == 'OFF_SHORE' and pDict["TEMPSOURCE"].value('value') == 'CALCULATED')
	pDict['SB_TEMP'].valueChange('enable', pDict["WELLLOC"].value('value') == 'OFF_SHORE' and pDict["TEMPSOURCE"].value('value') == 'CALCULATED')
	pDict['GL_DEP'].valueChange('enable', pDict["WELLLOC"].value('value') == 'ON_SHORE' and pDict["TEMPSOURCE"].value('value') == 'CALCULATED')

	pDict['TEMP_LOG'].valueChange('enable', pDict["TEMPSOURCE"].value('value') == 'LOG')
	pDict['SWT_METHOD'].valueChange('enable', pDict["SWT_FLAG"].value('value') == 'YES')
	pDict['CALCULATED_MSTAR'].valueChange('enable', pDict["SWT_FLAG"].value('value') == 'YES')
	pDict['M'].valueChange('enable', pDict["SWT_FLAG"].value('value') == 'YES')
	pDict['N'].valueChange('enable', pDict["SWT_FLAG"].value('value') == 'YES')
	pDict['SALFLG'].valueChange('enable', pDict["SWT_FLAG"].value('value') == 'YES')
	pDict['RW'].valueChange('enable', pDict["SWT_FLAG"].value('value') == 'YES' and pDict["SALFLG"].value('value') == 'NO')
	pDict['SALW'].valueChange('enable', pDict["SWT_FLAG"].value('value') == 'YES' and pDict["SALFLG"].value('value') == 'YES')
	pDict['CWBGRAD'].valueChange('enable', pDict["SWT_FLAG"].value('value') == 'YES' and pDict["SWT_METHOD"].value('value') == 'WAXMAN_SMITS' and pDict["QVFLAG"].value('value') == 'NO')
	pDict['QVFLAG'].valueChange('enable', pDict["SWT_FLAG"].value('value') == 'YES' and pDict["SWT_METHOD"].value('value') == 'WAXMAN_SMITS')
	pDict['QV_LOG'].valueChange('enable', pDict["SWT_FLAG"].value('value') == 'YES' and pDict["SWT_METHOD"].value('value') == 'WAXMAN_SMITS' and pDict["QVFLAG"].value('value') == 'YES')
	pDict['__________TEMP_PRM_SECTION'].valueChange('enable', 'X' in pDict["LITHOLOGY_MODEL"].value('value'))
	pDict['__________RW_PRM_SECTION'].valueChange('enable', 'X' in pDict["LITHOLOGY_MODEL"].value('value'))
	pDict['__________SAT_XPLOT_SECTION'].valueChange('enable', 'X' in pDict["LITHOLOGY_MODEL"].value('value'))
	pDict['PICKETT_PLOT'].valueChange('enable', pDict["SWT_FLAG"].value('value') == 'YES')
	pDict['CW_VCLPHIT_PLOT'].valueChange('enable', pDict["SWT_FLAG"].value('value') == 'YES' and pDict["SWT_METHOD"].value('value') == 'WAXMAN_SMITS')
	pDict['WATERZONE_DEPTH'].valueChange('enable', pDict["SWT_FLAG"].value('value') == 'YES' and (pDict['CW_VCLPHIT_PLOT'].value('value')=='YES' or pDict['PICKETT_PLOT'].value('value')=='YES'))
	pDict['__________FLUID_TYPE_PRM_SECTION'].valueChange('enable', 'X' in pDict["LITHOLOGY_MODEL"].value('value'))	
	pDict['HCTYPE_FLAG'].valueChange('enable', pDict["SWT_FLAG"].value('value') == 'YES')
	pDict['OGF'].valueChange('enable', pDict["SWT_FLAG"].value('value') == 'YES' and pDict["HCTYPE_FLAG"].value('value') == 'YES')
	pDict['__________BYPASS_PRM_SECTION'].valueChange('enable', 'X' in pDict["LITHOLOGY_MODEL"].value('value'))	
	pDict['BYPASS_LITHO_PORO_CALCULATION'].valueChange('enable', pDict["SWT_FLAG"].value('value') == 'YES')
	pDict['EXT_PHIT_LOG'].valueChange('enable', pDict["SWT_FLAG"].value('value') == 'YES' and pDict["BYPASS_LITHO_PORO_CALCULATION"].value('value') == 'YES')
	pDict['EXT_PHIE_LOG'].valueChange('enable', pDict["SWT_FLAG"].value('value') == 'YES' and pDict["BYPASS_LITHO_PORO_CALCULATION"].value('value') == 'YES')
	pDict['CLAY_VOLUME_FLAG'].valueChange('enable', pDict["SWT_FLAG"].value('value') == 'YES' and pDict["BYPASS_LITHO_PORO_CALCULATION"].value('value') == 'YES')
	pDict['EXT_VCLD_LOG'].valueChange('enable', pDict["SWT_FLAG"].value('value') == 'YES' and pDict["BYPASS_LITHO_PORO_CALCULATION"].value('value') == 'YES' and pDict["SWT_METHOD"].value('value') == 'WAXMAN_SMITS' and pDict["CLAY_VOLUME_FLAG"].value('value') == 'VCLD')
	pDict['OTHER_EXT_VCLY_LOG'].valueChange('enable', pDict["SWT_FLAG"].value('value') == 'YES' and pDict["BYPASS_LITHO_PORO_CALCULATION"].value('value') == 'YES' and pDict["SWT_METHOD"].value('value') == 'WAXMAN_SMITS' and pDict["CLAY_VOLUME_FLAG"].value('value') == 'OTHER_CLAY_VOL')
	pDict['__________HC_CORR_PRM_SECTION'].valueChange('enable', 'X' in pDict["LITHOLOGY_MODEL"].value('value'))
	pDict['HCC_APP'].valueChange('enable', pDict["SWT_FLAG"].value('value') == 'NO' or pDict["BYPASS_LITHO_PORO_CALCULATION"].value('value') == 'NO')
	pDict['HCCOR'].valueChange('enable', pDict["HCC_APP"].value('value') == 'YES')
	pDict['COR_METHOD'].valueChange('enable', pDict["HCC_APP"].value('value') == 'YES')
	pDict['NEUFAC'].valueChange('enable', pDict["COR_METHOD"].value('value') == 'EMPIRICAL' and pDict["HCC_APP"].value('value') == 'YES')
	pDict['RHO_GAS'].valueChange('enable', pDict["COR_METHOD"].value('value') in ('STANDARD','SECOND_METHOD') and pDict["HCC_APP"].value('value') == 'YES')
	pDict['RHO_OIL'].valueChange('enable', pDict["COR_METHOD"].value('value') in ('STANDARD','SECOND_METHOD') and pDict["HCC_APP"].value('value') == 'YES')
	pDict['MFRES'].valueChange('enable', pDict["COR_METHOD"].value('value') in ('STANDARD','SECOND_METHOD') and pDict["HCC_APP"].value('value') == 'YES')
	pDict['MFTEMP'].valueChange('enable', pDict["COR_METHOD"].value('value') in ('STANDARD','SECOND_METHOD') and pDict["HCC_APP"].value('value') == 'YES')
	pDict['DEGHCCOR'].valueChange('enable', pDict["COR_METHOD"].value('value') in ('FIX_ANGLE','THIRD_METHOD') and pDict["HCC_APP"].value('value') == 'YES')
	pDict['HCREF'].valueChange('enable', pDict["HCC_APP"].value('value') == 'YES')
	pDict['EXT_REF_LOG'].valueChange('enable', pDict["HCREF"].value('value') == 'EXTERNAL' and pDict["HCC_APP"].value('value') == 'YES')
	pDict['__________BH_CORR_PRM_SECTION'].valueChange('enable', 'X' in pDict["LITHOLOGY_MODEL"].value('value'))
	pDict['BH_CORR'].valueChange('enable', pDict["SWT_FLAG"].value('value') == 'NO' or pDict["BYPASS_LITHO_PORO_CALCULATION"].value('value') == 'NO')
	pDict['SOURCE_SYN_LOG'].valueChange('enable', pDict["BH_CORR"].value('value') == 'YES')
	pDict['SYNDENSD'].valueChange('enable', pDict["BH_CORR"].value('value') == 'YES')
	pDict['SYNDENCL'].valueChange('enable', pDict["BH_CORR"].value('value') == 'YES')
	pDict['EXTRHOBFLG'].valueChange('enable', pDict["BH_CORR"].value('value') == 'YES')
	pDict['CORR_RHOB_LOG'].valueChange('enable', pDict["EXTRHOBFLG"].value('value') == 'YES' and pDict["BH_CORR"].value('value') == 'YES')
	pDict['BHCTYP'].valueChange('enable',pDict["BH_CORR"].value('value') == 'YES')
	pDict['__________COAL_FLAG_PRM_SECTION'].valueChange('enable', 'X' in pDict["LITHOLOGY_MODEL"].value('value'))
	pDict['COALFL'].valueChange('enable', pDict["LITHOLOGY_MODEL"].value('value') == 'SSC')
	pDict['EXTCOAL'].valueChange('enable', pDict["COALFL"].value('value') == 'YES' and pDict["LITHOLOGY_MODEL"].value('value') == 'SSC' )
	pDict['COALCUT'].valueChange('enable', pDict["COALFL"].value('value') == 'YES' and pDict["LITHOLOGY_MODEL"].value('value') == 'SSC'and pDict["EXTCOAL"].value('value') == 'NO')
	pDict['COALFLAG_EXPANSION'].valueChange('enable', pDict["LITHOLOGY_MODEL"].value('value') == 'SSC' and pDict['COALFL'].value('value')=='YES' and pDict["EXTCOAL"].value('value') == 'NO')
	pDict['COALFLG_LOG'].valueChange('enable', pDict["EXTCOAL"].value('value') == 'YES' and pDict["COALFL"].value('value') == 'YES' and pDict["LITHOLOGY_MODEL"].value('value') == 'SSC')
	pDict['__________LIME_STREAK_PRM_SECTION'].valueChange('enable', 'X' in pDict["LITHOLOGY_MODEL"].value('value'))
	pDict['CARSTFL'].valueChange('enable', pDict["LITHOLOGY_MODEL"].value('value') == 'SSC')
	pDict['EXTSTREAK'].valueChange('enable', pDict["LITHOLOGY_MODEL"].value('value') == 'SSC'  and pDict['CARSTFL'].value('value')=='YES')
	pDict['STRCUT'].valueChange('enable', pDict["EXTSTREAK"].value('value') == 'NO' and pDict["CARSTFL"].value('value') == 'YES' and pDict["LITHOLOGY_MODEL"].value('value') == 'SSC')
	pDict['LMSTRKFLG_LOG'].valueChange('enable', pDict["EXTSTREAK"].value('value') == 'YES' and pDict["CARSTFL"].value('value') == 'YES' and pDict["LITHOLOGY_MODEL"].value('value') == 'SSC')
	pDict['__________UNC_ANALYSIS_SECTION'].valueChange('enable', 'X' in pDict["LITHOLOGY_MODEL"].value('value'))
	pDict['ITR_NO'].valueChange('enable', pDict["DO_MC"].value('value') == 'YES')
	pDict['P1P'].valueChange('enable', pDict["DO_MC"].value('value') == 'YES')
	pDict['P2P'].valueChange('enable', pDict["DO_MC"].value('value') == 'YES')
	pDict['P3P'].valueChange('enable', pDict["DO_MC"].value('value') == 'YES')
	pDict['MCLOG_SECTION'].valueChange('enable', pDict["DO_MC"].value('value') == 'YES')
	pDict['RHOB_LOG_DIST'].valueChange('enable', pDict["DO_MC"].value('value') == 'YES' and pDict["MCLOG_SECTION"].value('value') == 'EXPAND')
	pDict['ER_MIN_RHOB'].valueChange('enable', pDict["DO_MC"].value('value') == 'YES' and pDict["MCLOG_SECTION"].value('value') == 'EXPAND' and pDict["RHOB_LOG_DIST"].value('value') == 'Triangular')
	pDict['ER_MAX_RHOB'].valueChange('enable', pDict["DO_MC"].value('value') == 'YES' and pDict["MCLOG_SECTION"].value('value') == 'EXPAND' and pDict["RHOB_LOG_DIST"].value('value') == 'Triangular')
	pDict['PT_ERR_RHOB'].valueChange('enable', pDict["DO_MC"].value('value') == 'YES' and pDict["MCLOG_SECTION"].value('value') == 'EXPAND' and pDict["RHOB_LOG_DIST"].value('value') != 'Triangular')
	pDict['NPHI_LOG_DIST'].valueChange('enable', pDict["DO_MC"].value('value') == 'YES' and pDict["MCLOG_SECTION"].value('value') == 'EXPAND')
	pDict['ER_MIN_NPHI'].valueChange('enable', pDict["DO_MC"].value('value') == 'YES' and pDict["MCLOG_SECTION"].value('value') == 'EXPAND' and pDict["NPHI_LOG_DIST"].value('value') == 'Triangular')
	pDict['ER_MAX_NPHI'].valueChange('enable', pDict["DO_MC"].value('value') == 'YES' and pDict["MCLOG_SECTION"].value('value') == 'EXPAND' and pDict["NPHI_LOG_DIST"].value('value') == 'Triangular')
	pDict['PT_ERR_NPHI'].valueChange('enable', pDict["DO_MC"].value('value') == 'YES' and pDict["MCLOG_SECTION"].value('value') == 'EXPAND' and pDict["NPHI_LOG_DIST"].value('value') != 'Triangular')
	pDict['GR_LOG_DIST'].valueChange('enable', pDict["DO_MC"].value('value') == 'YES' and pDict["MCLOG_SECTION"].value('value') == 'EXPAND')
	pDict['ER_MIN_GR'].valueChange('enable', pDict["DO_MC"].value('value') == 'YES' and pDict["MCLOG_SECTION"].value('value') == 'EXPAND' and pDict["GR_LOG_DIST"].value('value') == 'Triangular')
	pDict['ER_MAX_GR'].valueChange('enable', pDict["DO_MC"].value('value') == 'YES' and pDict["MCLOG_SECTION"].value('value') == 'EXPAND' and pDict["GR_LOG_DIST"].value('value') == 'Triangular')
	pDict['PT_ERR_GR'].valueChange('enable', pDict["DO_MC"].value('value') == 'YES' and pDict["MCLOG_SECTION"].value('value') == 'EXPAND')
	pDict['RT_LOG_DIST'].valueChange('enable', pDict["DO_MC"].value('value') == 'YES' and pDict["MCLOG_SECTION"].value('value') == 'EXPAND')
	pDict['ER_MIN_RT'].valueChange('enable', pDict["DO_MC"].value('value') == 'YES' and pDict["MCLOG_SECTION"].value('value') == 'EXPAND' and pDict["RT_LOG_DIST"].value('value') == 'Triangular')
	pDict['ER_MAX_RT'].valueChange('enable', pDict["DO_MC"].value('value') == 'YES' and pDict["MCLOG_SECTION"].value('value') == 'EXPAND' and pDict["RT_LOG_DIST"].value('value') == 'Triangular')
	pDict['PT_ERR_RT'].valueChange('enable', pDict["DO_MC"].value('value') == 'YES' and pDict["MCLOG_SECTION"].value('value') == 'EXPAND' and pDict["RT_LOG_DIST"].value('value') != 'Triangular')
	pDict['MCSSC_SECTION'].valueChange('enable', pDict["DO_MC"].value('value') == 'YES')
	pDict['RHOB_CL_PAR_DIST'].valueChange('enable', pDict["DO_MC"].value('value') == 'YES' and pDict["MCSSC_SECTION"].value('value') == 'EXPAND')
	pDict['ER_MIN_RHOB_CL'].valueChange('enable', pDict["DO_MC"].value('value') == 'YES' and pDict["MCSSC_SECTION"].value('value') == 'EXPAND' and pDict["RHOB_CL_PAR_DIST"].value('value') == 'Triangular')
	pDict['ER_MAX_RHOB_CL'].valueChange('enable', pDict["DO_MC"].value('value') == 'YES' and pDict["MCSSC_SECTION"].value('value') == 'EXPAND' and pDict["RHOB_CL_PAR_DIST"].value('value') == 'Triangular')
	pDict['PT_ERR_RHOB_CL'].valueChange('enable', pDict["DO_MC"].value('value') == 'YES' and pDict["MCSSC_SECTION"].value('value') == 'EXPAND' and pDict["RHOB_CL_PAR_DIST"].value('value') != 'Triangular')
	pDict['RHODRYSD_PAR_DIST'].valueChange('enable', pDict["DO_MC"].value('value') == 'YES' and pDict["MCSSC_SECTION"].value('value') == 'EXPAND')
	pDict['ER_MIN_RHODRYSD'].valueChange('enable', pDict["DO_MC"].value('value') == 'YES' and pDict["MCSSC_SECTION"].value('value') == 'EXPAND' and pDict["RHODRYSD_PAR_DIST"].value('value') == 'Triangular')
	pDict['ER_MAX_RHODRYSD'].valueChange('enable', pDict["DO_MC"].value('value') == 'YES' and pDict["MCSSC_SECTION"].value('value') == 'EXPAND' and pDict["RHODRYSD_PAR_DIST"].value('value') == 'Triangular')
	pDict['PT_ERR_RHODRYSD'].valueChange('enable', pDict["DO_MC"].value('value') == 'YES' and pDict["MCSSC_SECTION"].value('value') == 'EXPAND' and pDict["RHODRYSD_PAR_DIST"].value('value') != 'Triangular')
	pDict['RHOB_DRYLM_PAR_DIST'].valueChange('enable', pDict["LITHOLOGY_MODEL"].value('value') == 'CARB' and pDict["DO_MC"].value('value') == 'YES' and pDict["MCSSC_SECTION"].value('value') == 'EXPAND')
	pDict['ER_MIN_RHOB_DRYLM'].valueChange('enable', pDict["LITHOLOGY_MODEL"].value('value') == 'CARB' and pDict["DO_MC"].value('value') == 'YES' and pDict["MCSSC_SECTION"].value('value') == 'EXPAND' and pDict["RHODRYSD_PAR_DIST"].value('value') == 'Triangular')
	pDict['ER_MAX_RHOB_DRYLM'].valueChange('enable', pDict["LITHOLOGY_MODEL"].value('value') == 'CARB' and pDict["DO_MC"].value('value') == 'YES' and pDict["MCSSC_SECTION"].value('value') == 'EXPAND' and pDict["RHODRYSD_PAR_DIST"].value('value') == 'Triangular')
	pDict['PT_ERR_RHOB_DRYLM'].valueChange('enable', pDict["LITHOLOGY_MODEL"].value('value') == 'CARB' and pDict["DO_MC"].value('value') == 'YES' and pDict["MCSSC_SECTION"].value('value') == 'EXPAND' and pDict["RHODRYSD_PAR_DIST"].value('value') != 'Triangular')
	pDict['RHOB_DRYDL_PAR_DIST'].valueChange('enable', pDict["LITHOLOGY_MODEL"].value('value') == 'CARB' and pDict["DO_MC"].value('value') == 'YES' and pDict["MCSSC_SECTION"].value('value') == 'EXPAND')
	pDict['ER_MIN_RHOB_DRYDL'].valueChange('enable', pDict["LITHOLOGY_MODEL"].value('value') == 'CARB' and pDict["DO_MC"].value('value') == 'YES' and pDict["MCSSC_SECTION"].value('value') == 'EXPAND' and pDict["RHODRYSD_PAR_DIST"].value('value') == 'Triangular')
	pDict['ER_MAX_RHOB_DRYDL'].valueChange('enable', pDict["LITHOLOGY_MODEL"].value('value') == 'CARB' and pDict["DO_MC"].value('value') == 'YES' and pDict["MCSSC_SECTION"].value('value') == 'EXPAND' and pDict["RHODRYSD_PAR_DIST"].value('value') == 'Triangular')
	pDict['PT_ERR_RHOB_DRYDL'].valueChange('enable', pDict["LITHOLOGY_MODEL"].value('value') == 'CARB' and pDict["DO_MC"].value('value') == 'YES' and pDict["MCSSC_SECTION"].value('value') == 'EXPAND' and pDict["RHODRYSD_PAR_DIST"].value('value') != 'Triangular')
	pDict['NPHI_CL_PAR_DIST'].valueChange('enable', pDict["DO_MC"].value('value') == 'YES' and pDict["MCSSC_SECTION"].value('value') == 'EXPAND')
	pDict['ER_MIN_NPHI_CL'].valueChange('enable', pDict["DO_MC"].value('value') == 'YES' and pDict["MCSSC_SECTION"].value('value') == 'EXPAND' and pDict["NPHI_CL_PAR_DIST"].value('value') == 'Triangular')
	pDict['ER_MAX_NPHI_CL'].valueChange('enable', pDict["DO_MC"].value('value') == 'YES' and pDict["MCSSC_SECTION"].value('value') == 'EXPAND' and pDict["NPHI_CL_PAR_DIST"].value('value') == 'Triangular')
	pDict['PT_ERR_NPHI_CL'].valueChange('enable', pDict["DO_MC"].value('value') == 'YES' and pDict["MCSSC_SECTION"].value('value') == 'EXPAND' and pDict["NPHI_CL_PAR_DIST"].value('value') != 'Triangular')
	pDict['NPHI_DRYSD_PAR_DIST'].valueChange('enable', pDict["DO_MC"].value('value') == 'YES' and pDict["MCSSC_SECTION"].value('value') == 'EXPAND')
	pDict['ER_MIN_NPHI_DRYSD'].valueChange('enable', pDict["DO_MC"].value('value') == 'YES' and pDict["MCSSC_SECTION"].value('value') == 'EXPAND' and pDict["NPHI_DRYSD_PAR_DIST"].value('value') == 'Triangular')
	pDict['ER_MAX_NPHI_DRYSD'].valueChange('enable', pDict["DO_MC"].value('value') == 'YES' and pDict["MCSSC_SECTION"].value('value') == 'EXPAND' and pDict["NPHI_DRYSD_PAR_DIST"].value('value') == 'Triangular')
	pDict['PT_ERR_NPHI_DRYSD'].valueChange('enable', pDict["DO_MC"].value('value') == 'YES' and pDict["MCSSC_SECTION"].value('value') == 'EXPAND' and pDict["NPHI_DRYSD_PAR_DIST"].value('value') != 'Triangular')
	pDict['NPHI_DRYLM_PAR_DIST'].valueChange('enable', pDict["LITHOLOGY_MODEL"].value('value') == 'CARB' and pDict["DO_MC"].value('value') == 'YES' and pDict["MCSSC_SECTION"].value('value') == 'EXPAND')
	pDict['ER_MIN_NPHI_DRYLM'].valueChange('enable', pDict["LITHOLOGY_MODEL"].value('value') == 'CARB' and pDict["DO_MC"].value('value') == 'YES' and pDict["MCSSC_SECTION"].value('value') == 'EXPAND' and pDict["NPHI_DRYSD_PAR_DIST"].value('value') == 'Triangular')
	pDict['ER_MAX_NPHI_DRYLM'].valueChange('enable', pDict["LITHOLOGY_MODEL"].value('value') == 'CARB' and pDict["DO_MC"].value('value') == 'YES' and pDict["MCSSC_SECTION"].value('value') == 'EXPAND' and pDict["NPHI_DRYSD_PAR_DIST"].value('value') == 'Triangular')
	pDict['PT_ERR_NPHI_DRYLM'].valueChange('enable', pDict["LITHOLOGY_MODEL"].value('value') == 'CARB' and pDict["DO_MC"].value('value') == 'YES' and pDict["MCSSC_SECTION"].value('value') == 'EXPAND' and pDict["NPHI_DRYSD_PAR_DIST"].value('value') != 'Triangular')
	pDict['NPHI_DRYDL_PAR_DIST'].valueChange('enable', pDict["LITHOLOGY_MODEL"].value('value') == 'CARB' and pDict["DO_MC"].value('value') == 'YES' and pDict["MCSSC_SECTION"].value('value') == 'EXPAND')
	pDict['ER_MIN_NPHI_DRYDL'].valueChange('enable', pDict["LITHOLOGY_MODEL"].value('value') == 'CARB' and pDict["DO_MC"].value('value') == 'YES' and pDict["MCSSC_SECTION"].value('value') == 'EXPAND' and pDict["NPHI_DRYSD_PAR_DIST"].value('value') == 'Triangular')
	pDict['ER_MAX_NPHI_DRYDL'].valueChange('enable', pDict["LITHOLOGY_MODEL"].value('value') == 'CARB' and pDict["DO_MC"].value('value') == 'YES' and pDict["MCSSC_SECTION"].value('value') == 'EXPAND' and pDict["NPHI_DRYSD_PAR_DIST"].value('value') == 'Triangular')
	pDict['PT_ERR_NPHI_DRYDL'].valueChange('enable', pDict["LITHOLOGY_MODEL"].value('value') == 'CARB' and pDict["DO_MC"].value('value') == 'YES' and pDict["MCSSC_SECTION"].value('value') == 'EXPAND' and pDict["NPHI_DRYSD_PAR_DIST"].value('value') != 'Triangular')
	pDict['SILTLINE_RATIO_PAR_DIST'].valueChange('enable', pDict["DO_MC"].value('value') == 'YES' and pDict["MCSSC_SECTION"].value('value') == 'EXPAND')
	pDict['ER_MIN_SILTLINE_RATIO'].valueChange('enable', pDict["DO_MC"].value('value') == 'YES' and pDict["MCSSC_SECTION"].value('value') == 'EXPAND' and pDict["SILTLINE_RATIO_PAR_DIST"].value('value') == 'Triangular')
	pDict['ER_MAX_SILTLINE_RATIO'].valueChange('enable', pDict["DO_MC"].value('value') == 'YES' and pDict["MCSSC_SECTION"].value('value') == 'EXPAND' and pDict["SILTLINE_RATIO_PAR_DIST"].value('value') == 'Triangular')
	pDict['PT_ERR_SILTLINE_RATIO'].valueChange('enable', pDict["DO_MC"].value('value') == 'YES' and pDict["MCSSC_SECTION"].value('value') == 'EXPAND' and pDict["SILTLINE_RATIO_PAR_DIST"].value('value') != 'Triangular')
	pDict['RHODRYSL_PAR_DIST'].valueChange('enable', pDict["DO_MC"].value('value') == 'YES' and pDict["MCSSC_SECTION"].value('value') == 'EXPAND')
	pDict['ER_MIN_RHODRYSL'].valueChange('enable', pDict["DO_MC"].value('value') == 'YES' and pDict["MCSSC_SECTION"].value('value') == 'EXPAND' and pDict["RHODRYSL_PAR_DIST"].value('value') == 'Triangular')
	pDict['ER_MAX_RHODRYSL'].valueChange('enable', pDict["DO_MC"].value('value') == 'YES' and pDict["MCSSC_SECTION"].value('value') == 'EXPAND' and pDict["RHODRYSL_PAR_DIST"].value('value') == 'Triangular')
	pDict['PT_ERR_RHODRYSL'].valueChange('enable', pDict["DO_MC"].value('value') == 'YES' and pDict["MCSSC_SECTION"].value('value') == 'EXPAND' and pDict["RHODRYSL_PAR_DIST"].value('value') != 'Triangular')
	pDict['MCSW_SECTION'].valueChange('enable', pDict["DO_MC"].value('value') == 'YES')
	pDict['RW_PAR_DIST'].valueChange('enable', pDict["DO_MC"].value('value') == 'YES' and pDict["MCSW_SECTION"].value('value') == 'EXPAND')
	pDict['ER_MIN_RW'].valueChange('enable', pDict["DO_MC"].value('value') == 'YES' and pDict["MCSW_SECTION"].value('value') == 'EXPAND' and pDict["RW_PAR_DIST"].value('value') == 'Triangular')
	pDict['ER_MAX_RW'].valueChange('enable', pDict["DO_MC"].value('value') == 'YES' and pDict["MCSW_SECTION"].value('value') == 'EXPAND' and pDict["RW_PAR_DIST"].value('value') == 'Triangular')
	pDict['PT_ERR_RW'].valueChange('enable', pDict["DO_MC"].value('value') == 'YES' and pDict["MCSW_SECTION"].value('value') == 'EXPAND' and pDict["RW_PAR_DIST"].value('value') != 'Triangular')
	pDict['CWBGRAD_PAR_DIST'].valueChange('enable', pDict["DO_MC"].value('value') == 'YES' and pDict["MCSW_SECTION"].value('value') == 'EXPAND')
	pDict['ER_MAX_CWBGRAD'].valueChange('enable', pDict["DO_MC"].value('value') == 'YES' and pDict["MCSW_SECTION"].value('value') == 'EXPAND' and pDict["CWBGRAD_PAR_DIST"].value('value') == 'Triangular')
	pDict['ER_MIN_CWBGRAD'].valueChange('enable', pDict["DO_MC"].value('value') == 'YES' and pDict["MCSW_SECTION"].value('value') == 'EXPAND' and pDict["CWBGRAD_PAR_DIST"].value('value') == 'Triangular')
	pDict['PT_ERR_CWBGRAD'].valueChange('enable', pDict["DO_MC"].value('value') == 'YES' and pDict["MCSW_SECTION"].value('value') == 'EXPAND' and pDict["CWBGRAD_PAR_DIST"].value('value') != 'Triangular')
	pDict['M_PAR_DIST'].valueChange('enable', pDict["DO_MC"].value('value') == 'YES' and pDict["MCSW_SECTION"].value('value') == 'EXPAND')
	pDict['ER_MIN_M'].valueChange('enable', pDict["DO_MC"].value('value') == 'YES' and pDict["MCSW_SECTION"].value('value') == 'EXPAND' and pDict["M_PAR_DIST"].value('value') == 'Triangular')
	pDict['ER_MAX_M'].valueChange('enable', pDict["DO_MC"].value('value') == 'YES' and pDict["MCSW_SECTION"].value('value') == 'EXPAND' and pDict["M_PAR_DIST"].value('value') == 'Triangular')
	pDict['PT_ERR_M'].valueChange('enable', pDict["DO_MC"].value('value') == 'YES' and pDict["MCSW_SECTION"].value('value') == 'EXPAND' and pDict["M_PAR_DIST"].value('value') != 'Triangular')
	pDict['N_PAR_DIST'].valueChange('enable', pDict["DO_MC"].value('value') == 'YES' and pDict["MCSW_SECTION"].value('value') == 'EXPAND')
	pDict['ER_MIN_N'].valueChange('enable', pDict["DO_MC"].value('value') == 'YES' and pDict["MCSW_SECTION"].value('value') == 'EXPAND' and pDict["N_PAR_DIST"].value('value') == 'Triangular')
	pDict['ER_MAX_N'].valueChange('enable', pDict["DO_MC"].value('value') == 'YES' and pDict["MCSW_SECTION"].value('value') == 'EXPAND' and pDict["N_PAR_DIST"].value('value') == 'Triangular')
	pDict['PT_ERR_N'].valueChange('enable', pDict["DO_MC"].value('value') == 'YES' and pDict["MCSW_SECTION"].value('value') == 'EXPAND' and pDict["N_PAR_DIST"].value('value') != 'Triangular')
	pDict['GR_COR_SECTION'].valueChange('enable', pDict["DO_MC"].value('value') == 'YES' and (pDict["HCC_APP"].value('value') == 'YES' or pDict["BH_CORR"].value('value') == 'YES'))
	pDict['GR_SD_PAR_DIST'].valueChange('enable', pDict["DO_MC"].value('value') == 'YES' and pDict["GR_COR_SECTION"].value('value') == 'EXPAND' and (pDict["HCC_APP"].value('value') == 'YES' or pDict["BH_CORR"].value('value') == 'YES'))
	pDict['ER_MIN_GR_SD'].valueChange('enable', pDict["DO_MC"].value('value') == 'YES' and pDict["GR_COR_SECTION"].value('value') == 'EXPAND' and pDict["GR_SD_PAR_DIST"].value('value') == 'Triangular' and (pDict["HCC_APP"].value('value') == 'YES' or pDict["BH_CORR"].value('value') == 'YES'))
	pDict['ER_MAX_GR_SD'].valueChange('enable', pDict["DO_MC"].value('value') == 'YES' and pDict["GR_COR_SECTION"].value('value') == 'EXPAND' and pDict["GR_SD_PAR_DIST"].value('value') == 'Triangular' and (pDict["HCC_APP"].value('value') == 'YES' or pDict["BH_CORR"].value('value') == 'YES'))
	pDict['PT_ERR_GR_SD'].valueChange('enable', pDict["DO_MC"].value('value') == 'YES' and pDict["GR_COR_SECTION"].value('value') == 'EXPAND' and pDict["GR_SD_PAR_DIST"].value('value') != 'Triangular' and (pDict["HCC_APP"].value('value') == 'YES' or pDict["BH_CORR"].value('value') == 'YES'))
	pDict['GR_CL_PAR_DIST'].valueChange('enable', pDict["DO_MC"].value('value') == 'YES' and pDict["GR_COR_SECTION"].value('value') == 'EXPAND' and (pDict["HCC_APP"].value('value') == 'YES' or pDict["BH_CORR"].value('value') == 'YES'))
	pDict['ER_MIN_GR_CL'].valueChange('enable', pDict["DO_MC"].value('value') == 'YES' and pDict["GR_COR_SECTION"].value('value') == 'EXPAND' and pDict["GR_CL_PAR_DIST"].value('value') == 'Triangular' and (pDict["HCC_APP"].value('value') == 'YES' or pDict["BH_CORR"].value('value') == 'YES'))
	pDict['ER_MAX_GR_CL'].valueChange('enable', pDict["DO_MC"].value('value') == 'YES' and pDict["GR_COR_SECTION"].value('value') == 'EXPAND' and pDict["GR_CL_PAR_DIST"].value('value') == 'Triangular' and (pDict["HCC_APP"].value('value') == 'YES' or pDict["BH_CORR"].value('value') == 'YES'))
	pDict['PT_ERR_GR_CL'].valueChange('enable', pDict["DO_MC"].value('value') == 'YES' and pDict["GR_COR_SECTION"].value('value') == 'EXPAND' and pDict["GR_CL_PAR_DIST"].value('value') != 'Triangular' and (pDict["HCC_APP"].value('value') == 'YES' or pDict["BH_CORR"].value('value') == 'YES'))
	pDict['MCHC_SECTION'].valueChange('enable', pDict["DO_MC"].value('value') == 'YES' and pDict["HCC_APP"].value('value') == 'YES')
	pDict['RHOGAS_PAR_DIST'].valueChange('enable', pDict["DO_MC"].value('value') == 'YES' and pDict["MCHC_SECTION"].value('value') == 'EXPAND' and pDict["COR_METHOD"].value('value') == 'STANDARD' and pDict["HCC_APP"].value('value') == 'YES')
	pDict['ER_MIN_RHOGAS'].valueChange('enable', pDict["DO_MC"].value('value') == 'YES' and pDict["MCHC_SECTION"].value('value') == 'EXPAND' and pDict["RHOGAS_PAR_DIST"].value('value') == 'Triangular' and pDict["COR_METHOD"].value('value') == 'STANDARD' and pDict["HCC_APP"].value('value') == 'YES')
	pDict['ER_MAX_RHOGAS'].valueChange('enable', pDict["DO_MC"].value('value') == 'YES' and pDict["MCHC_SECTION"].value('value') == 'EXPAND' and pDict["RHOGAS_PAR_DIST"].value('value') == 'Triangular' and pDict["COR_METHOD"].value('value') == 'STANDARD' and pDict["HCC_APP"].value('value') == 'YES')
	pDict['PT_ERR_RHOGAS'].valueChange('enable', pDict["DO_MC"].value('value') == 'YES' and pDict["MCHC_SECTION"].value('value') == 'EXPAND' and pDict["RHOGAS_PAR_DIST"].value('value') != 'Triangular' and pDict["COR_METHOD"].value('value') == 'STANDARD' and pDict["HCC_APP"].value('value') == 'YES')
	pDict['RHOOIL_PAR_DIST'].valueChange('enable', pDict["DO_MC"].value('value') == 'YES' and pDict["MCHC_SECTION"].value('value') == 'EXPAND' and pDict["COR_METHOD"].value('value') == 'STANDARD' and pDict["HCC_APP"].value('value') == 'YES')
	pDict['PT_ERR_RHOOIL'].valueChange('enable', pDict["DO_MC"].value('value') == 'YES' and pDict["MCHC_SECTION"].value('value') == 'EXPAND' and pDict["RHOOIL_PAR_DIST"].value('value') != 'Triangular' and pDict["COR_METHOD"].value('value') == 'STANDARD' and pDict["HCC_APP"].value('value') == 'YES')
	pDict['ER_MAX_RHOOIL'].valueChange('enable', pDict["DO_MC"].value('value') == 'YES' and pDict["MCHC_SECTION"].value('value') == 'EXPAND' and pDict["RHOOIL_PAR_DIST"].value('value') == 'Triangular' and pDict["COR_METHOD"].value('value') == 'STANDARD' and pDict["HCC_APP"].value('value') == 'YES')
	pDict['ER_MIN_RHOOIL'].valueChange('enable', pDict["DO_MC"].value('value') == 'YES' and pDict["MCHC_SECTION"].value('value') == 'EXPAND' and pDict["RHOOIL_PAR_DIST"].value('value') == 'Triangular' and pDict["COR_METHOD"].value('value') == 'STANDARD' and pDict["HCC_APP"].value('value') == 'YES')
	pDict['MFRES_PAR_DIST'].valueChange('enable', pDict["DO_MC"].value('value') == 'YES' and pDict["MCHC_SECTION"].value('value') == 'EXPAND' and pDict["COR_METHOD"].value('value') == 'STANDARD' and pDict["HCC_APP"].value('value') == 'YES')
	pDict['ER_MIN_MFRES'].valueChange('enable', pDict["DO_MC"].value('value') == 'YES' and pDict["MCHC_SECTION"].value('value') == 'EXPAND' and pDict["MFRES_PAR_DIST"].value('value') == 'Triangular' and pDict["COR_METHOD"].value('value') == 'STANDARD' and pDict["HCC_APP"].value('value') == 'YES')
	pDict['ER_MAX_MFRES'].valueChange('enable', pDict["DO_MC"].value('value') == 'YES' and pDict["MCHC_SECTION"].value('value') == 'EXPAND' and pDict["MFRES_PAR_DIST"].value('value') == 'Triangular' and pDict["COR_METHOD"].value('value') == 'STANDARD' and pDict["HCC_APP"].value('value') == 'YES')
	pDict['PT_ERR_MFRES'].valueChange('enable', pDict["DO_MC"].value('value') == 'YES' and pDict["MCHC_SECTION"].value('value') == 'EXPAND' and pDict["MFRES_PAR_DIST"].value('value') != 'Triangular' and pDict["COR_METHOD"].value('value') == 'STANDARD' and pDict["HCC_APP"].value('value') == 'YES')
	pDict['NEUFAC_PAR_DIST'].valueChange('enable', pDict["DO_MC"].value('value') == 'YES' and pDict["MCHC_SECTION"].value('value') == 'EXPAND' and pDict["COR_METHOD"].value('value') == 'EMPIRICAL' and pDict["HCC_APP"].value('value') == 'YES')
	pDict['ER_MIN_NEUFAC'].valueChange('enable', pDict["DO_MC"].value('value') == 'YES' and pDict["MCHC_SECTION"].value('value') == 'EXPAND' and pDict["NEUFAC_PAR_DIST"].value('value') == 'Triangular' and pDict["COR_METHOD"].value('value') == 'EMPIRICAL' and pDict["HCC_APP"].value('value') == 'YES')
	pDict['ER_MAX_NEUFAC'].valueChange('enable', pDict["DO_MC"].value('value') == 'YES' and pDict["MCHC_SECTION"].value('value') == 'EXPAND' and pDict["NEUFAC_PAR_DIST"].value('value') == 'Triangular' and pDict["COR_METHOD"].value('value') == 'EMPIRICAL' and pDict["HCC_APP"].value('value') == 'YES')
	pDict['PT_ERR_NEUFAC'].valueChange('enable', pDict["DO_MC"].value('value') == 'YES' and pDict["MCHC_SECTION"].value('value') == 'EXPAND' and pDict["NEUFAC_PAR_DIST"].value('value') != 'Triangular' and pDict["COR_METHOD"].value('value') == 'EMPIRICAL' and pDict["HCC_APP"].value('value') == 'YES')
	pDict['DEGHCCOR_PAR_DIST'].valueChange('enable', pDict["DO_MC"].value('value') == 'YES' and pDict["MCHC_SECTION"].value('value') == 'EXPAND' and pDict["COR_METHOD"].value('value') == 'FIX_ANGLE' and pDict["HCC_APP"].value('value') == 'YES')
	pDict['ER_MIN_DEGHCCOR'].valueChange('enable', pDict["DO_MC"].value('value') == 'YES' and pDict["MCHC_SECTION"].value('value') == 'EXPAND' and pDict["DEGHCCOR_PAR_DIST"].value('value') == 'Triangular' and pDict["COR_METHOD"].value('value') == 'FIX_ANGLE' and pDict["HCC_APP"].value('value') == 'YES')
	pDict['ER_MAX_DEGHCCOR'].valueChange('enable', pDict["DO_MC"].value('value') == 'YES' and pDict["MCHC_SECTION"].value('value') == 'EXPAND' and pDict["DEGHCCOR_PAR_DIST"].value('value') == 'Triangular' and pDict["COR_METHOD"].value('value') == 'FIX_ANGLE' and pDict["HCC_APP"].value('value') == 'YES')
	pDict['PT_ERR_DEGHCCOR'].valueChange('enable', pDict["DO_MC"].value('value') == 'YES' and pDict["MCHC_SECTION"].value('value') == 'EXPAND' and pDict["DEGHCCOR_PAR_DIST"].value('value') != 'Triangular' and pDict["COR_METHOD"].value('value') == 'FIX_ANGLE' and pDict["HCC_APP"].value('value') == 'YES')
	pDict['MCBH_SECTION'].valueChange('enable', pDict["DO_MC"].value('value') == 'YES' and pDict["BH_CORR"].value('value') == 'YES')
	pDict['SYNDENSD_PAR_DIST'].valueChange('enable', pDict["DO_MC"].value('value') == 'YES' and pDict["MCBH_SECTION"].value('value') == 'EXPAND' and pDict["BH_CORR"].value('value') == 'YES')
	pDict['ER_MIN_SYNDENSD'].valueChange('enable', pDict["DO_MC"].value('value') == 'YES' and pDict["MCBH_SECTION"].value('value') == 'EXPAND' and pDict["SYNDENSD_PAR_DIST"].value('value') == 'Triangular' and pDict["BH_CORR"].value('value') == 'YES')
	pDict['ER_MAX_SYNDENSD'].valueChange('enable', pDict["DO_MC"].value('value') == 'YES' and pDict["MCBH_SECTION"].value('value') == 'EXPAND' and pDict["SYNDENSD_PAR_DIST"].value('value') == 'Triangular' and pDict["BH_CORR"].value('value') == 'YES')
	pDict['PT_ERR_SYNDENSD'].valueChange('enable', pDict["DO_MC"].value('value') == 'YES' and pDict["MCBH_SECTION"].value('value') == 'EXPAND' and pDict["SYNDENSD_PAR_DIST"].value('value') != 'Triangular' and pDict["BH_CORR"].value('value') == 'YES')
	pDict['SYNDENCL_PAR_DIST'].valueChange('enable', pDict["DO_MC"].value('value') == 'YES' and pDict["MCBH_SECTION"].value('value') == 'EXPAND' and pDict["BH_CORR"].value('value') == 'YES')
	pDict['ER_MIN_SYNDENCL'].valueChange('enable', pDict["DO_MC"].value('value') == 'YES' and pDict["MCBH_SECTION"].value('value') == 'EXPAND' and pDict["SYNDENCL_PAR_DIST"].value('value') == 'Triangular' and pDict["BH_CORR"].value('value') == 'YES')
	pDict['ER_MAX_SYNDENCL'].valueChange('enable', pDict["DO_MC"].value('value') == 'YES' and pDict["MCBH_SECTION"].value('value') == 'EXPAND' and pDict["SYNDENCL_PAR_DIST"].value('value') == 'Triangular' and pDict["BH_CORR"].value('value') == 'YES')
	pDict['PT_ERR_SYNDENCL'].valueChange('enable', pDict["DO_MC"].value('value') == 'YES' and pDict["MCBH_SECTION"].value('value') == 'EXPAND' and pDict["SYNDENCL_PAR_DIST"].value('value') != 'Triangular' and pDict["BH_CORR"].value('value') == 'YES')
	pDict['PEF'].valueChange('enable', pDict["LITHOLOGY_MODEL"].value('value') == 'CARB')
	pDict['TVDSS'].valueChange('enable', pDict["DEPTHSOURCE"].value('value') == 'DEPTH_TVDSS')
	pDict['VCLW_MIN'].valueChange('enable', pDict["DO_MC"].value('value') == 'YES')
	pDict['VCLW_MAX'].valueChange('enable', pDict["DO_MC"].value('value') == 'YES')
	pDict['VSILT_MIN'].valueChange('enable', pDict["DO_MC"].value('value') == 'YES')
	pDict['VSILT_MAX'].valueChange('enable', pDict["DO_MC"].value('value') == 'YES')
	pDict['PHIT_MIN'].valueChange('enable', pDict["DO_MC"].value('value') == 'YES')
	pDict['PHIT_MAX'].valueChange('enable', pDict["DO_MC"].value('value') == 'YES')
	pDict['SWT_MIN'].valueChange('enable', pDict["DO_MC"].value('value') == 'YES')
	pDict['SWT_MAX'].valueChange('enable', pDict["DO_MC"].value('value') == 'YES')
	pDict['PHIT_D'].valueChange('enable', pDict["DO_MC"].value('value') == 'YES')
	pDict['SWT_D'].valueChange('enable', pDict["DO_MC"].value('value') == 'YES')
	pDict['VCLW_D'].valueChange('enable', pDict["DO_MC"].value('value') == 'YES')
	pDict['VSILT_D'].valueChange('enable', pDict["DO_MC"].value('value') == 'YES')
	pDict['VCLW_MEAN'].valueChange('enable', pDict["DO_MC"].value('value') == 'YES')
	pDict['VCLW_1P'].valueChange('enable', pDict["DO_MC"].value('value') == 'YES')
	pDict['VCLW_2P'].valueChange('enable', pDict["DO_MC"].value('value') == 'YES')
	pDict['VCLW_3P'].valueChange('enable', pDict["DO_MC"].value('value') == 'YES')
	pDict['VSILT_MEAN'].valueChange('enable', pDict["DO_MC"].value('value') == 'YES')
	pDict['VSILT_1P'].valueChange('enable', pDict["DO_MC"].value('value') == 'YES')
	pDict['VSILT_2P'].valueChange('enable', pDict["DO_MC"].value('value') == 'YES')
	pDict['VSILT_3P'].valueChange('enable', pDict["DO_MC"].value('value') == 'YES')
	pDict['PHIT_MEAN'].valueChange('enable', pDict["DO_MC"].value('value') == 'YES')
	pDict['PHIT_1P'].valueChange('enable', pDict["DO_MC"].value('value') == 'YES')
	pDict['PHIT_2P'].valueChange('enable', pDict["DO_MC"].value('value') == 'YES')
	pDict['PHIT_3P'].valueChange('enable', pDict["DO_MC"].value('value') == 'YES')
	pDict['SWT_MEAN'].valueChange('enable', pDict["DO_MC"].value('value') == 'YES')
	pDict['SWT_1P'].valueChange('enable', pDict["DO_MC"].value('value') == 'YES')
	pDict['SWT_2P'].valueChange('enable', pDict["DO_MC"].value('value') == 'YES')
	pDict['SWT_3P'].valueChange('enable', pDict["DO_MC"].value('value') == 'YES')
	pDict['RHOB_LO'].valueChange('enable', pDict["DO_MC"].value('value') == 'YES')
	pDict['RHOB_HI'].valueChange('enable', pDict["DO_MC"].value('value') == 'YES')
	pDict['NPHI_LO'].valueChange('enable', pDict["DO_MC"].value('value') == 'YES')
	pDict['NPHI_HI'].valueChange('enable', pDict["DO_MC"].value('value') == 'YES')
	pDict['GR_LO'].valueChange('enable', pDict["DO_MC"].value('value') == 'YES')
	pDict['GR_HI'].valueChange('enable', pDict["DO_MC"].value('value') == 'YES')
	pDict['RT_LO'].valueChange('enable', pDict["DO_MC"].value('value') == 'YES')
	pDict['RT_HI'].valueChange('enable', pDict["DO_MC"].value('value') == 'YES')

__pyVersion__ = """3"""